# Generated by Django 4.2.14 on 2024-08-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_sale',
            field=models.BooleanField(default=False),
        ),
    ]
