# Generated by Django 4.2.16 on 2024-09-06 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orders',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart'),
        ),
    ]
